In [12]:
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
import pandas as pd

In [13]:
#dataset --> https://www.kaggle.com/datasets/yasserh/housing-prices-dataset
df = pd.read_csv("../DataSet/Housing.csv")

In [14]:
data = pd.get_dummies(df, drop_first=True)

In [15]:
data.head()

price  ...  furnishingstatus_unfurnished
0  13300000  ...                         False
1  12250000  ...                         False
2  12250000  ...                         False
3  12215000  ...                         False
4  11410000  ...                         False

[5 rows x 14 columns]

In [16]:
x = data.iloc[ : , 1: ]

In [17]:
x.head()

area  ...  furnishingstatus_unfurnished
0  7420  ...                         False
1  8960  ...                         False
2  9960  ...                         False
3  7500  ...                         False
4  7420  ...                         False

[5 rows x 13 columns]

In [18]:
y = data.iloc[: , 0]

In [19]:
y.head()

0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
Name: price, dtype: int64

# Normalization

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [31]:
xdata = sc.fit_transform(x)
ydata = sc.fit_transform(y.values.reshape(-1, 1)).ravel()

In [32]:
xdata, ydata

(array([[ 1.04672629,  1.40341936,  1.42181174, ...,  1.80494113,
         -0.84488844, -0.6964292 ],
        [ 1.75700953,  1.40341936,  5.40580863, ..., -0.55403469,
         -0.84488844, -0.6964292 ],
        [ 2.21823241,  0.04727831,  1.42181174, ...,  1.80494113,
          1.18358821, -0.6964292 ],
        ...,
        [-0.70592066, -1.30886273, -0.57018671, ..., -0.55403469,
         -0.84488844,  1.43589615],
        [-1.03338891,  0.04727831, -0.57018671, ..., -0.55403469,
         -0.84488844, -0.6964292 ],
        [-0.5998394 ,  0.04727831, -0.57018671, ..., -0.55403469,
         -0.84488844,  1.43589615]]),
 array([ 4.56636513e+00,  4.00448405e+00,  4.00448405e+00,  3.98575468e+00,
         3.55497918e+00,  3.25530927e+00,  2.88072189e+00,  2.88072189e+00,
         2.73088693e+00,  2.69342819e+00,  2.69342819e+00,  2.62974834e+00,
         2.43121702e+00,  2.39375829e+00,  2.39375829e+00,  2.31884081e+00,
         2.31884081e+00,  2.24392333e+00,  2.20646459e+00,  2.1877352

In [33]:
x_train, x_test, y_train, y_test = train_test_split(xdata, ydata, random_state=0) # herea random state help to give same result of split when ever run the code

# Train a Model

In [61]:
model = SVR(kernel="linear")

In [62]:
model.fit(x_train, y_train)

SVR(kernel='linear')

In [63]:
model.intercept_

array([-0.03828618])

In [64]:
model.support_

array([  0,   1,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  18,  19,  20,  21,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  48,  49,  50,  51,  52,  53,  54,  55,
        57,  58,  59,  60,  61,  63,  64,  65,  67,  68,  69,  70,  72,
        73,  75,  76,  78,  79,  80,  81,  82,  83,  84,  85,  86,  88,
        89,  90,  91,  92,  94,  95,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 111, 112, 114, 115, 116, 117, 118,
       120, 121, 125, 126, 128, 130, 131, 132, 133, 134, 135, 136, 137,
       138, 139, 140, 141, 142, 143, 145, 146, 147, 148, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180,
       181, 182, 183, 184, 185, 186, 188, 189, 190, 192, 193, 194, 195,
       197, 198, 200, 201, 202, 203, 204, 207, 208, 209, 210, 21

In [65]:
y_pred = model.predict(x_test)

In [66]:
from sklearn.metrics import r2_score

In [67]:
r2_score(y_test, y_pred)

0.7056083456105271

# Export model

In [52]:
import joblib

In [53]:
joblib.dump(model, "svr.joblib")

['svr.joblib']

# Load model and predict

In [43]:
loadedmodel = joblib.load("svr.joblib")

In [44]:
loadedmodel.predict([[7420, 4, 2, 3, 2, True, False, False, False, True, True, False, False]])

array([1936.7131077])